% getTQBSatNodes.m
% This function calculates the Trigonometric Quintic B-spline (TQB)
% basis function matrix T at a given set of nodes.
% The TQB basis functions are defined over a uniform grid.

% Inputs:
% x: A row vector of spatial nodes (grid points) where the TQB basis
%    functions are to be evaluated.

% Output:
% T: The (N+1) x (M+4) matrix where N+1 is the number of grid points
%    and M+4 is the number of TQB basis functions.
%    T(i, j) = Value of the j-th TQB basis function at the i-th grid point.

function T = getTQBSatNodes(x)
    
    % Initialize the matrices for the basis functions and their derivatives
    N = length(x);
    d1 = abs(x(2)-x(1)); d2 = abs(x(end)-x(end-1));
    T = zeros(N,N+4);
    
    % Define the fucntions to build the piecewise-defined quintic basis function.
    X = @(x,y) sin((y-x)/2);
    S = @(x,y) sin((x-y)/2);
    
    % Update x with ghost points    
    x = [x(1)-6*d1 x(1)-5*d1 x(1)-4*d1 x(1)-3*d1 x(1)-2*d1 x(1)-d1 x x(end)+d2 x(end)+2*d2 x(end)+3*d2 x(end)+4*d2 x(end)+5*d2 x(end)+6*d2]; 

    % Define the trigonometric basis functions T_k(x)
    % These are the building blocks for the TQB splines.
    % The basis functions are piecewise trigonometric polynomials.

    % The local basis function is shifted for each j.
    for j = 7:N+6
        y = x(j);
        i = j+2;
        T(j-6,j+4-6) = ((X(x(i-3),y).^4) .* S(x(i-1),y))./(S(x(i-1),x(i-2)) * S(x(i-1),x(i-3)) * S(x(i),x(i-3)) * S(x(i+1),x(i-3)) * S(x(i+2),x(i-3))) + ...
        ((X(x(i-3),y).^3) .* (S(x(i),y).^1) .* (X(x(i-2),y).^1))./(S(x(i-1),x(i-2)) * S(x(i),x(i-2)) * S(x(i),x(i-3)) * S(x(i+1),x(i-3)) * S(x(i+2),x(i-3))) + ...
        ((X(x(i-3),y).^2) .* (S(x(i+1),y).^1) .* (X(x(i-2),y).^2))./(S(x(i-1),x(i-2)) * S(x(i),x(i-2)) * S(x(i+1),x(i-2)) * S(x(i+1),x(i-3)) * S(x(i+2),x(i-3))) + ...
        ((X(x(i-3),y).^1) .* (S(x(i+2),y).^1) .* (X(x(i-2),y).^3))./(S(x(i-1),x(i-2)) * S(x(i),x(i-2)) * S(x(i+1),x(i-2)) * S(x(i+2),x(i-2)) * S(x(i+2),x(i-3))) + ...
        ((S(x(i+3),y).^1) .* (X(x(i-2),y).^4))./(S(x(i-1),x(i-2)) * S(x(i),x(i-2)) * S(x(i+1),x(i-2)) * S(x(i+2),x(i-2)) * S(x(i+3),x(i-2)));

        i = j+1;
        T(j-6,j+3-6) = ((X(x(i-3),y).^3) .* (S(x(i),y).^2))./(S(x(i),x(i-1)) * S(x(i),x(i-2)) * S(x(i),x(i-3)) * S(x(i+1),x(i-3)) * S(x(i+2),x(i-3))) + ...
         ((X(x(i-3),y).^2) .* (S(x(i+1),y)) .* (X(x(i-2),y)) .* (S(x(i),y)))./(S(x(i),x(i-1)) * S(x(i),x(i-2)) * S(x(i+1),x(i-2)) * S(x(i+1),x(i-3)) * S(x(i+2),x(i-3))) + ...
         ((X(x(i-3),y).^2) .* (S(x(i+1),y).^2) .* X(x(i-1),y))./(S(x(i),x(i-1)) * S(x(i+1),x(i-1)) * S(x(i+1),x(i-2)) * S(x(i+1),x(i-3)) * S(x(i+2),x(i-3))) +...
         ((X(x(i-3),y)) .* (S(x(i+2),y)) .* (X(x(i-2),y).^2) .* (S(x(i),y)))./(S(x(i),x(i-1)) * S(x(i),x(i-2)) * S(x(i+1),x(i-2)) * S(x(i+2),x(i-2)) * S(x(i+2),x(i-3))) + ...
         ((X(x(i-3),y)) .* (S(x(i+2),y)) .* (X(x(i-2),y)) .* (S(x(i+1),y)) .* (X(x(i-1),y)))./(S(x(i),x(i-1)) * S(x(i+1),x(i-1)) * S(x(i+1),x(i-2)) * S(x(i+2),x(i-2)) * S(x(i+2),x(i-3))) + ...
         ((X(x(i-3),y)) .* (S(x(i+2),y).^2) .* (X(x(i-1),y).^2))./(S(x(i),x(i-1)) * S(x(i+1),x(i-1)) * S(x(i+2),x(i-1)) * S(x(i+2),x(i-2)) * S(x(i+2),x(i-3)))  + ...
         ((S(x(i+3),y)) .* (X(x(i-2),y).^3) .* (S(x(i),y)))./(S(x(i),x(i-1)) * S(x(i),x(i-2)) * S(x(i+1),x(i-2)) * S(x(i+2),x(i-2)) * S(x(i+3),x(i-2))) + ...
         ((S(x(i+3),y)) .* (X(x(i-2),y).^2) .* (S(x(i+1),y)) .* (X(x(i-1),y)))./(S(x(i),x(i-1)) * S(x(i+1),x(i-1)) * S(x(i+1),x(i-2)) * S(x(i+2),x(i-2)) * S(x(i+3),x(i-2))) + ...
         ((S(x(i+3),y)) .* (X(x(i-2),y)) .* (S(x(i+2),y)) .* (X(x(i-1),y).^2))./(S(x(i),x(i-1)) * S(x(i+1),x(i-1)) * S(x(i+2),x(i-1)) * S(x(i+2),x(i-2)) * S(x(i+3),x(i-2))) + ...
         ((S(x(i+3),y).^2) .* (X(x(i-1),y).^3))./(S(x(i),x(i-1)) * S(x(i+1),x(i-1)) * S(x(i+2),x(i-1)) * S(x(i+3),x(i-1)) * S(x(i+3),x(i-2)));

        i = j;
        T(j-6,j+2-6) = ((X(x(i-3),y).^2) .* (S(x(i+1),y).^3))./(S(x(i+1),x(i)) * S(x(i+1),x(i-1)) * S(x(i+1),x(i-2)) * S(x(i+1),x(i-3)) * S(x(i+2),x(i-3))) + ...
         ((X(x(i-3),y)) .* (S(x(i+2),y)) .* (X(x(i-2),y)) .* (S(x(i+1),y).^2))./(S(x(i+1),x(i)) * S(x(i+1),x(i-1)) * S(x(i+1),x(i-2)) * S(x(i+2),x(i-2)) * S(x(i+2),x(i-3))) + ...
         ((X(x(i-3),y)) .* (S(x(i+2),y).^2) .* X(x(i-1),y) .* (S(x(i+1),y)))./(S(x(i+1),x(i)) * S(x(i+1),x(i-1)) * S(x(i+2),x(i-1)) * S(x(i+2),x(i-2)) * S(x(i+2),x(i-3)))+...
         ((X(x(i-3),y)) .* (S(x(i+2),y).^3) .* (X(x(i),y)))./(S(x(i+1),x(i)) * S(x(i+2),x(i)) * S(x(i+2),x(i-1)) * S(x(i+2),x(i-2)) * S(x(i+2),x(i-3)))  + ...
         ((S(x(i+3),y)) .* (X(x(i-2),y).^2) .* (S(x(i+1),y).^2))./(S(x(i+1),x(i)) * S(x(i+1),x(i-1)) * S(x(i+1),x(i-2)) * S(x(i+2),x(i-2)) * S(x(i+3),x(i-2))) + ...
         ((S(x(i+3),y)) .* (X(x(i-2),y)) .* (S(x(i+2),y)) .* (X(x(i-1),y)) .* (S(x(i+1),y)))./(S(x(i+1),x(i)) * S(x(i+1),x(i-1)) * S(x(i+2),x(i-1)) * S(x(i+2),x(i-2)) * S(x(i+3),x(i-2))) +...
         ((S(x(i+3),y)) .* (X(x(i-2),y)) .* (S(x(i+2),y).^2) .* (X(x(i),y)))./(S(x(i+1),x(i)) * S(x(i+2),x(i)) * S(x(i+2),x(i-1)) * S(x(i+2),x(i-2)) * S(x(i+3),x(i-2))) + ...
         ((S(x(i+3),y).^2) .* (X(x(i-1),y).^2) .* (S(x(i+1),y)))./(S(x(i+1),x(i)) * S(x(i+1),x(i-1)) * S(x(i+2),x(i-1)) * S(x(i+3),x(i-1)) * S(x(i+3),x(i-2))) +...
         ((S(x(i+3),y).^2) .* (X(x(i-1),y)) .* (S(x(i+2),y)) .* (X(x(i),y)))./(S(x(i+1),x(i)) * S(x(i+2),x(i)) * S(x(i+2),x(i-1)) * S(x(i+3),x(i-1)) * S(x(i+3),x(i-2))) + ...
         ((S(x(i+3),y).^3) .* (X(x(i),y).^2))./(S(x(i+1),x(i)) * S(x(i+2),x(i)) * S(x(i+3),x(i)) * S(x(i+3),x(i-1)) * S(x(i+3),x(i-2)));

        i = j-1;
        T(j-6,j+1-6) = ((X(x(i-3),y)) .* (S(x(i+2),y).^4))./(S(x(i+2),x(i+1)) * S(x(i+2),x(i)) * S(x(i+2),x(i-1)) * S(x(i+2),x(i-2)) * S(x(i+2),x(i-3))) + ...
        ((S(x(i+3),y)) .* (X(x(i-2),y)) .* (S(x(i+2),y).^3))./(S(x(i+2),x(i+1)) * S(x(i+2),x(i)) * S(x(i+2),x(i-1)) * S(x(i+2),x(i-2)) * S(x(i+3),x(i-2))) + ...
        ((S(x(i+3),y).^2) .* (X(x(i-1),y)) .* (S(x(i+2),y).^2))./(S(x(i+2),x(i+1)) * S(x(i+2),x(i)) * S(x(i+2),x(i-1)) * S(x(i+3),x(i-1)) * S(x(i+3),x(i-2))) + ...
        ((S(x(i+3),y).^3) .* (X(x(i),y)) .* (S(x(i+2),y)))./(S(x(i+2),x(i+1)) * S(x(i+2),x(i)) * S(x(i+3),x(i)) * S(x(i+3),x(i-1)) * S(x(i+3),x(i-2))) + ...
        ((S(x(i+3),y).^4) .* (X(x(i+1),y)))./(S(x(i+2),x(i+1)) * S(x(i+3),x(i+1)) * S(x(i+3),x(i)) * S(x(i+3),x(i-1)) * S(x(i+3),x(i-2)));
        i = j-2;
        T(j-6,j-6) = (S(x(i+3),y).^5)./(S(x(i+3),x(i+2)) * S(x(i+3),x(i+1)) * S(x(i+3),x(i)) * S(x(i+3),x(i-1)) * S(x(i+3),x(i-2)));
    end
end